services:
  qdrant:
    # https://hub.docker.com/r/qdrant/qdrant/tags
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes:
      - ./data/qdrant:/qdrant/storage
      - ./qdrant_config.yml:/qdrant/config/production.yaml
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
    ports:
      - 6333:6333
      - 6334:6334